services:
  caddy:
    ports: !override
      - "8080:80"
      - "8081:443"
      - "8081:443/udp"
    expose:
      - "80"
      - "443"
      - "443/udp"
    networks:
      - default
      - external

networks:
  external:
    external: true
